import {PERMISSIONS, ALL_PERMISSIONS} from './permissions.js';

/**
 * Default system roles for WooWooErp Admin RBAC (Step 3).
 * Permissions must come from the catalog — never invent keys here.
 */

const P = PERMISSIONS;

export const DEFAULT_ROLES = Object.freeze([
  {
    name: 'Super Admin',
    slug: 'super_admin',
    description: 'Full system access including Access Control.',
    isSystem: true,
    permissions: [...ALL_PERMISSIONS],
  },
  {
    name: 'Admin',
    slug: 'admin',
    description: 'Full business access except managing Access Control roles.',
    isSystem: true,
    permissions: ALL_PERMISSIONS.filter(key => key !== P.ACCESS_MANAGE),
  },
  {
    name: 'Cashier',
    slug: 'cashier',
    description: 'POS / invoices, customers, and basic catalogue viewing.',
    isSystem: true,
    permissions: [
      P.DASHBOARD_READ,
      P.COMPANY_READ,
      P.INVOICE_READ,
      P.INVOICE_CREATE,
      P.INVOICE_UPDATE,
      P.QUOTATION_READ,
      P.QUOTATION_CREATE,
      P.CREDIT_NOTE_READ,
      P.CREDIT_NOTE_CREATE,
      P.SUBSCRIPTION_READ,
      P.SUBSCRIPTION_CREATE,
      P.CUSTOMER_READ,
      P.CUSTOMER_CREATE,
      P.CUSTOMER_UPDATE,
      P.PRODUCT_READ,
      P.SERVICE_READ,
      P.SPACE_READ,
      P.FOOD_READ,
      P.MEMBERSHIP_PLAN_READ,
    ],
  },
  {
    name: 'Catalogue Editor',
    slug: 'catalogue_editor',
    description: 'Manage products, services, spaces, foods, and plans.',
    isSystem: true,
    permissions: [
      P.DASHBOARD_READ,
      P.COMPANY_READ,
      P.PRODUCT_READ,
      P.PRODUCT_CREATE,
      P.PRODUCT_UPDATE,
      P.PRODUCT_DELETE,
      P.SERVICE_READ,
      P.SERVICE_CREATE,
      P.SERVICE_UPDATE,
      P.SERVICE_DELETE,
      P.SPACE_READ,
      P.SPACE_CREATE,
      P.SPACE_UPDATE,
      P.SPACE_DELETE,
      P.FOOD_READ,
      P.FOOD_CREATE,
      P.FOOD_UPDATE,
      P.FOOD_DELETE,
      P.MEMBERSHIP_PLAN_READ,
      P.MEMBERSHIP_PLAN_MANAGE,
      P.CATEGORY_MANAGE,
    ],
  },
  {
    name: 'Purchase Clerk',
    slug: 'purchase_clerk',
    description: 'Purchases, purchase orders, debit notes, vendors, inventory view.',
    isSystem: true,
    permissions: [
      P.DASHBOARD_READ,
      P.COMPANY_READ,
      P.PURCHASE_READ,
      P.PURCHASE_CREATE,
      P.PURCHASE_UPDATE,
      P.PURCHASE_ORDER_READ,
      P.PURCHASE_ORDER_CREATE,
      P.PURCHASE_ORDER_UPDATE,
      P.DEBIT_NOTE_READ,
      P.DEBIT_NOTE_CREATE,
      P.VENDOR_READ,
      P.VENDOR_CREATE,
      P.VENDOR_UPDATE,
      P.INVENTORY_READ,
      P.INVENTORY_TIMELINE_READ,
      P.PRODUCT_READ,
    ],
  },
  {
    name: 'Viewer',
    slug: 'viewer',
    description: 'Read-only access to common modules.',
    isSystem: true,
    permissions: [
      P.DASHBOARD_READ,
      P.COMPANY_READ,
      P.INVOICE_READ,
      P.QUOTATION_READ,
      P.CREDIT_NOTE_READ,
      P.SUBSCRIPTION_READ,
      P.PURCHASE_READ,
      P.PURCHASE_ORDER_READ,
      P.DEBIT_NOTE_READ,
      P.INVENTORY_READ,
      P.INVENTORY_TIMELINE_READ,
      P.PRODUCT_READ,
      P.SERVICE_READ,
      P.SPACE_READ,
      P.FOOD_READ,
      P.MEMBERSHIP_PLAN_READ,
      P.CUSTOMER_READ,
      P.VENDOR_READ,
      P.WALLET_READ,
      P.COUPON_READ,
      P.AFFILIATE_READ,
    ],
  },
]);
